name: ng2_fontawesome
version: 4.7.0+4
description: Font Awesome for Angular2
authors:
  - Mark E. Haase <mehaase@gmail.com>
homepage: https://github.com/hyperiongray/ng2_fontawesome

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  angular: '^4.0.0'
