name: ng_fontawesome
version: 4.7.0+7
description: >
  Contains directives for using glyphs from the popular Font Awesome library.

authors:
  - Mark E. Haase <mehaase@gmail.com>
homepage: https://github.com/hyperiongray/ng_fontawesome

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  angular: '^4.0.0'

transformers:
- angular
